### ISSUE TITLE
상수처리가 필요합니다.

### ISSUE THREAD

**Issue by jungyoun** [nerdchanii/codsparring-client#13]
https://github.com/nerdchanii/codsparring-client/blob/a702a475b626ff4b41f2bb7aa358f4c9e4564afc/src/state/ide/index.jsx#L4

https://github.com/nerdchanii/codsparring-client/blob/a702a475b626ff4b41f2bb7aa358f4c9e4564afc/src/state/ide/index.jsx#L25

이런 부분은 상수처리를 해주면 좋습니다.

```
key: 'todoListState',
```
는
```
const TODO_LIST_STATE = ...
...
key: TODO_LIST_STATE,
```
이렇게 처리해주시면 좋고 

```
case 'cpp':
```
는
```
const CPP = ...
```
이렇게 처리해주면 좋습니다.
```
const LANG_TYPE = {
    CPP: ...
```
이런식으로 댑스를 줘도 좋습니다.

암튼 저런 것은 상수처리를 해야 작업하다가 오타가 나거나 하는 것을 막을 수 있습니다.

**Comment by jungyoun** [comment]
상수를 쓸 때 이렇게 switch문을 쓰게되면 Symbol("CPP") 이런식으로 상수를 만들어 낼 수도 있는데 Symbol로 쓰는 것은 ie구버전에서 안되는 문제랑 Symbol 자체의 특성이 있는게 있으니 한번 고려해보세요. 정 모르겠으면 당장은 안써도 됩니다. 있다는 것만 알고 선택해보세여.

**Comment by nerdchanii** [comment]
심볼을 적용해 보지는 못했지만..! 일단 심볼은 확인했습니다! 감사합니다 👍🏻
