### ISSUE TITLE
계속 함수가 재정의 되는 문제

### ISSUE THREAD

**Issue by jungyoun** [nerdchanii/codsparring-client#14]
https://github.com/nerdchanii/codsparring-client/blob/a702a475b626ff4b41f2bb7aa358f4c9e4564afc/src/components/Problem/ProblemContainer.jsx#L11-L54

이렇게 처리할 경우 fetchData함수가 계속 재정의될텐데 다른방법을 찾아보면 좋을 것 같아요.

**Comment by nerdchanii** [comment]
[src/components/leaderboard/BoardList.jsx](https://github.com/nerdchanii/codsparring-client/blob/4727bb9246732ffc9e3354cb37affb420ab6d70a/src/components/leaderboard/BoardList.jsx)와 [src/components/Problem/ProblemList.jsx](https://github.com/nerdchanii/codsparring-client/blob/4727bb9246732ffc9e3354cb37affb420ab6d70a/src/components/Problem/ProblemList.jsx)의 fetchData도 재정의되는 것을 막아야합니다.
